# Generated by Django 3.1.2 on 2020-10-28 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contnet_type', models.CharField(choices=[('AV', 'Article View'), ('OT', 'Only Text'), ('OI', 'Only Image')], default='OI', max_length=2)),
                ('content_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('SPORT', 'Sport'), ('SOCIAL', 'Social'), ('PROGRAMMING', 'Programming'), ('PLITICAL', 'Political'), ('CINEMA', 'Movie And Cinema'), ('HEALTH', 'Health'), ('MUSIC', 'Music'), ('GAMING', 'Gaming'), ('FUN', 'Fun'), ('NEWS', 'News'), ('MEME', 'Memes'), ('TECH', 'Technology'), ('AD', 'Art And Design'), ('FOOD', 'Food'), ('EDU', 'Education'), ('SCIENCE', 'Science'), ('BOOK', 'Book And Wrting'), ('BEUTY', 'Beuty'), ('DISCUSSION', 'Discussion'), ('QA', 'Q & A'), ('MEDICIAN', 'Medician'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.content')),
            ],
        ),
    ]
