# Generated by Django 3.1.2 on 2021-02-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reports_number',
            field=models.IntegerField(default=0),
        ),
    ]
