# Generated by Django 3.1.2 on 2020-10-31 18:53

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20201031_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(null=True, upload_to=posts.models.get_image_directory),
        ),
    ]
