# Generated by Django 3.1.2 on 2020-12-13 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0009_auto_20201121_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.post')),
            ],
            bases=('posts.post',),
        ),
    ]
