# Generated by Django 3.1.2 on 2021-02-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsubject',
            name='text',
            field=models.CharField(choices=[(1, 'Sexual Content'), (2, 'Insult'), (3, 'Violent'), (4, 'Other'), (5, 'Racist')], max_length=20),
        ),
    ]
