# Generated by Django 3.1.2 on 2020-12-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20201228_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsubject',
            name='text',
            field=models.CharField(choices=[(1, 'insult'), (2, 'sexual content'), (3, 'sensetve content')], max_length=20),
        ),
    ]
