# Generated by Django 3.1.2 on 2021-01-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20201228_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsubject',
            name='text',
            field=models.CharField(choices=[(1, 'Sexual Content'), (2, 'Insult'), (3, 'Violent'), (4, 'Other')], max_length=20),
        ),
    ]
