# Generated by Django 3.1.2 on 2021-02-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='authentication_key',
            field=models.TextField(default='NULL', max_length=1000),
            preserve_default=False,
        ),
    ]
