# Generated by Django 3.1.2 on 2020-12-18 15:11

import chat.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20201212_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_image', models.BooleanField()),
                ('file', models.FileField(upload_to=chat.models.get_chat_dir)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.directchatmessage')),
            ],
        ),
    ]
