# Generated by Django 3.1.2 on 2020-12-24 12:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='directchatmessage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
