# Generated by Django 3.1.2 on 2020-12-24 12:45

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20201224_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directchatmessage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
