# Generated by Django 3.1.2 on 2020-12-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20201224_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='directchatmessage',
            name='file_type',
            field=models.IntegerField(default=0),
        ),
    ]
