# Generated by Django 3.1.2 on 2020-11-06 15:38

import community.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=750)),
                ('image', models.ImageField(upload_to=community.models.get_community_images_directory)),
                ('back_image', models.ImageField(upload_to=community.models.get_community_backimages_directory)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_community', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='in_community', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
