# Generated by Django 3.1.2 on 2020-11-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20201106_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='back_image',
            new_name='banner_picture',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='image',
            new_name='picture',
        ),
    ]
