# Generated by Django 3.1.2 on 2020-12-25 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0003_auto_20201109_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='disabeled_users',
            field=models.ManyToManyField(related_name='disabeled_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
