# Generated by Django 3.1.2 on 2020-11-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('icon', models.CharField(max_length=100)),
                ('name', models.CharField(choices=[('A', 'Art'), ('H', 'Health'), ('M', 'Music'), ('FS', 'Film & Series'), ('SP', 'Sport'), ('P', 'Politics'), ('C', 'Computers'), ('FA', 'Fashion'), ('FO', 'Food'), ('TR', 'Travel'), ('G', 'Games'), ('SC', 'Science'), ('NA', 'Nature'), ('PS', 'Psychology'), ('PR', 'Programming'), ('F', 'Fun'), ('NE', 'News'), ('M', 'Meme'), ('TE', 'Technology'), ('B', 'Book And Wrting')], max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
