# Generated by Django 3.1.2 on 2021-02-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('icon', models.CharField(max_length=100)),
                ('name', models.CharField(choices=[('A', 'Art'), ('B', 'Books'), ('C', 'Computers'), ('FA', 'Fashion'), ('FS', 'Films'), ('FO', 'Food'), ('FU', 'Fun'), ('G', 'Games'), ('T', 'TV Series'), ('H', 'Health'), ('M', 'Music'), ('NE', 'News'), ('NA', 'Nature'), ('P', 'Politics'), ('PS', 'Psychology'), ('SC', 'Science'), ('TE', 'Technology'), ('TR', 'Travel')], max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
