# Generated by Django 3.1.2 on 2020-11-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('A', 'Art'), ('B', 'Books'), ('C', 'Computers'), ('FA', 'Fashion'), ('FS', 'Films'), ('FO', 'Food'), ('FU', 'Fun'), ('G', 'Games'), ('T', 'TV Series'), ('H', 'Health'), ('M', 'Music'), ('NE', 'News'), ('NA', 'Nature'), ('P', 'Politics'), ('PS', 'Psychology'), ('SC', 'Science'), ('TE', 'Technology'), ('TR', 'Travel')], max_length=50, primary_key=True, serialize=False),
        ),
    ]
