# Generated by Django 3.1.2 on 2020-11-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20201110_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default='Comment!', max_length=300),
        ),
    ]
